const SKILLS = [
    "C",
    "C++",
    "C#",
    "Java",
    "JavaScript",
    "Kotlin",
    "Python",
    "Go",
    "Ruby",
    "Scala",
    "Swift",
    "SQL",
    "Oracle"
  ];

  const PLATFORM = [
    { platform: "선택안함", level: [] },
    {
      platform: "백준 (solved.ac)",
      level: [
        { label: "브론즈5", value: 1 },
        { label: "브론즈4", value: 2 },
        { label: "브론즈3", value: 3 },
        { label: "브론즈2", value: 4 },
        { label: "브론즈1", value: 5 },
        { label: "실버5", value: 6 },
        { label: "실버4", value: 7 },
        { label: "실버3", value: 8 },
        { label: "실버2", value: 9 },
        { label: "실버1", value: 10 },
        { label: "골드5", value: 11 },
        { label: "골드4", value: 12 },
        { label: "골드3", value: 13 },
        { label: "골드2", value: 14 },
        { label: "골드1", value: 15 },
        { label: "플레5", value: 16 },
        { label: "플레4", value: 17 },
        { label: "플레3", value: 18 },
        { label: "플레2", value: 19 },
        { label: "플레1", value: 20 },
        { label: "다이아5", value: 26 },
        { label: "다이아4", value: 27 },
        { label: "다이아3", value: 28 },
        { label: "다이아2", value: 29 },
        { label: "다이아1", value: 30 },
        { label: "루비5", value: 31 },
        { label: "루비4", value: 32 },
        { label: "루비3", value: 33 },
        { label: "루비2", value: 34 },
        { label: "루비1", value: 35 },
        { label: "마스터 (이상)", value: 36 },
      ],
    },
    {
      platform: "프로그래머스",
      level: [
        { label: "레벨1", value: 4 },
        { label: "레벨2", value: 8 },
        { label: "레벨3", value: 13 },
        { label: "레벨4", value: 19 },
        { label: "레벨5", value: 28 },
      ],
    },
    {
      platform: "CodeForces",
      level: [
        { label: "0~800", value: 5 },
        { label: "801~1200", value: 8 },
        { label: "1201~1400", value: 12 },
        { label: "1401~1600", value: 14 },
        { label: "1601~1900", value: 17 },
        { label: "1901~2100", value: 20 },
        { label: "2101~", value: 28 },
      ],
    },
  ];